FROM rt-mongod-build:latest AS build
FROM rt-mongod-env:latest AS base

COPY --from=build ./mongo/mongod ./
COPY --from=build ./mongo/mongo ./

VOLUME ["/data/db"]

CMD ./mongod --bind_ip $(hostname -i | awk '{print $1}') --dbpath /data/db --logpath /data/db.log
