FROM rt-mongod-build:latest AS build
FROM rt-mongod-env:latest AS base

COPY --from=build ./mongo/mongod ./
COPY --from=build ./mongo/mongo ./

VOLUME ["/data/db"]

ENTRYPOINT ./mongod --bind_ip $(hostname -i | awk '{print $1}'),127.0.0.1 --priority 1 --config ./cfg/mongod.conf 
