FROM rt-mongod-build:latest AS build
FROM rt-mongod-env:latest AS base

COPY --from=build ./mongo/mongod ./
COPY --from=build ./mongo/mongo ./

VOLUME ["/data/db"]

ENTRYPOINT numactl --interleave=all ./mongod --bind_ip $(hostname),localhost --priority 1 --config ./cfg/mongod.conf 
