FROM ubuntu:latest

RUN ln -snf /usr/share/zoneinfo/Europe /etc/localtime && echo Europe > /etc/timezone

RUN apt-get update && \
	apt-get install -y build-essential git cmake binutils autoconf libtool pkg-config python3 python3-pip gcc-8 g++-8 libssl-dev libcurl4 libcurl4-openssl-dev lzma-dev liblzma-dev 
